/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import Pestañas.Tap1;
import Pestañas.Tap2;
import Pestañas.Tap3;
import Pestañas.Tap4;

/**
 *
 * @author PC
 */
public class Main_Menu extends javax.swing.JFrame implements Runnable {

    public static String usuario=Connect.user;
    /**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        
        Funciones.Apariencia();
        initComponents(); 
        
        
   
       
        Tap1 P1 = new Tap1();  Paneles.add("Publicidad", P1);
        Tap2 P2 = new Tap2();   
        Tap3 P3 = new Tap3(); 
        Tap4 P4 = new Tap4();
        
        switch(usuario){
            case "hira" :   
            User.setText("Brandon Martínez");   UserType.setText("Administrador"); 
            Paneles.add("Citas", P2); Paneles.add("Buscar", P3); Paneles.add("Agendar", P4); break;
            case "dante" :  
            User.setText("Jairo Martínez");   UserType.setText("Profesional");  
            Paneles.add("Citas", P2);   break;
        }         
        
         hilo = new Thread(this);
         hilo.start();
         setVisible(true);
       
    }

Thread hilo;
int cont;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserType = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Paneles = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserType.setText("Tipo de Usuario");
        getContentPane().add(UserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 19));

        User.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setText("Usuario");
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        Hora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hora.setText("Hora");
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 120, 19));

        Fecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha.setText("Fecha");
        Fecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 120, 19));
        getContentPane().add(Paneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 71, 670, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MainMenu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JTabbedPane Paneles;
    private javax.swing.JLabel User;
    private javax.swing.JLabel UserType;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

@Override
    public void run() {
    Thread current = Thread.currentThread();
    
    while(current==hilo){
        Funciones.hora();
        Hora.setText(Funciones.Hour+" : "+Funciones.Minute+" "+Funciones.ampm);
        Fecha.setText(Funciones.Day+" / "+Funciones.Month+" / "+Funciones.Year);
    }}
}