/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pestañas;

import HCE.HCE;
import Programa.Connect;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.logging.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author PC
 */
public class Tap2 extends javax.swing.JPanel {

    /**
     * Creates new form Tap2
     */
    public Tap2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbCitas = new javax.swing.JTable();
        JBtexit = new javax.swing.JButton();
        jBtActualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cedula", "Fecha", "Hora"
            }
        ));
        jScrollPane1.setViewportView(jTbCitas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 280));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 600, 320));

        JBtexit.setText("Cerrar Sesion");
        JBtexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtexitActionPerformed(evt);
            }
        });
        add(JBtexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jBtActualizar.setText("Actualizar");
        jBtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtActualizarActionPerformed(evt);
            }
        });
        add(jBtActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 100, -1));

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sin título.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));
    }// </editor-fold>//GEN-END:initComponents

    

    private void jBtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtActualizarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)jTbCitas.getModel();
        int a = jTbCitas.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        modelo.removeRow(modelo.getRowCount()-1);
        }try{
                Connect.con = Connect.con = (Connection) DriverManager.getConnection(Connect.url, Connect.user, Connect.pass);
                Statement pst = Connect.con.createStatement();
                ResultSet rs = pst.executeQuery("SELECT * FROM citas");
                rs.first();
                        do{
                            String[] tabla = {rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                            modelo.addRow(tabla);
                         }while(rs.next());
                }
                catch (SQLException ex) {
                    System.out.println("Error : " + ex);
                }
    }//GEN-LAST:event_jBtActualizarActionPerformed

    private void JBtexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtexitActionPerformed
                System.exit(0);
    }//GEN-LAST:event_JBtexitActionPerformed

    public static String OpUser, Cedula, Nombre;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cedula = (String) jTbCitas.getValueAt(jTbCitas.getSelectedRow(), 1);
        Nombre = (String) jTbCitas.getValueAt(jTbCitas.getSelectedRow(), 0);
        Object[] Op = {"Crear nueva","Ver antigua"};
        OpUser = (String) JOptionPane.showInputDialog(null, "Escoje una opción", "Historia Clinica Electronica", JOptionPane.INFORMATION_MESSAGE, null, Op, null);
        new HCE().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtexit;
    private javax.swing.JButton jBtActualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbCitas;
    // End of variables declaration//GEN-END:variables
}
